server:
  port: 8080
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/carsdb
    username: ${PG_USERNAME}
    password: ${PG_PASSWORD}
  main:
    web-application-type: servlet
  flyway:
    baseline-on-migrate: true