server:
  port: 8080
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/carsdb
    username: pguser
    password: password
  main:
    web-application-type: servlet